### ISSUE TITLE
Manage native-image-support-java in com.google.cloud:libraries-bom

### ISSUE THREAD

**Issue by ppalaga** [GoogleCloudPlatform/native-image-support-java#235]
The human readable [info in the README](https://github.com/GoogleCloudPlatform/native-image-support-java#client-library-versions) is useful, but rather impractical for a long term maintenance of a project that uses both `com.google.cloud:libraries-bom` and `native-image-support-java`.

Would it please be possible to manage `native-image-support-java` in `com.google.cloud:libraries-bom` so that users automatically get a combination compatible with eachother?

**Comment by dzou** [comment]
Just an fyi, the work to achieving this is currently in progress as we try to bring this project to GA.

**Comment by mpeddada1** [comment]
Hi @ppalaga Circling back on this: If you are using version 25.4.0 or later of the libraries-bom, the Cloud Client Libraries for Java come with the native image configurations built-in.

**Comment by mpeddada1** [comment]
That's right. You shouldn't need the `native-image-support` dependency anymore. Additionally, please check out this [document](https://cloud.google.com/java/docs/compile-native-images) which contains more info on how native image compilation works with the client libraries.

**Comment by dzou** [comment]
Hehe, great work @mpeddada1!!!
