### ISSUE TITLE
The samples show message "--initialize-at-build-time without arguments has been deprecated when not using --diagnostics-mode"

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/native-image-support-java#252]
In `native-image-samples-client-library/bigquery-sample`, running `mvn package -P native` showed the following message:

```
[bigquery-sample:80586]    classlist:   3,097.20 ms,  0.96 GB
--initialize-at-build-time without arguments has been deprecated when not using --diagnostics-mode. With GraalVM 22.0.0 --initialize-at-build-time will only work with --diagnostics-mode for debugging purposes.
The reason for deprecation is that --initalize-at-build-time does not compose, i.e., a single library can make assumptions that the whole classpath can be safely initialized at build time; that assumption is often incorrect.
```

<img width="675" alt="Screen Shot 2021-11-03 at 5 05 50 PM" src="https://user-images.githubusercontent.com/28604/140192718-b94c972f-5bda-4cfd-adc0-d0357429d0bc.png">

**Comment by mpeddada1** [comment]
Closing the loop on this: The [sample](https://github.com/googleapis/java-bigquery/blob/07197ebbdba7ee62dc2e2485cd79a5a9a9b3dfd5/samples/native-image-sample/pom.xml#L131) no longer includes `--initialize-at-build-time` without arguments.
