### ISSUE TITLE
[Question] How to use environment service account at run time

### ISSUE THREAD

**Issue by christiangoudreau** [GoogleCloudPlatform/native-image-support-java#332]
Hi, 

Maybe it's just me that doesn't quite have a grasp yet on how to use native image correctly, but it my build workflow, we're building only one image for every single environments that we have, then use environment variables to configure at run time those containers.

Wtih native image support, it seems to me like I'm supposed to give the service account for gcloud at build time. But then again, I have different service account for each environement.

Can anyone point me in the right direction as to understand how to do that in a "best pratice" way ? 

Thanks,

**Comment by suztomo** [comment]
>  it seems to me like I'm supposed to give the service account for gcloud at build time

Would you describe your finding a bit more? I believe native-image shouldn't change how service account is chosen between native-image runtime and normal JVM runtime. (but I may be wrong)

**Comment by dzou** [comment]
> Wtih native image support, it seems to me like I'm supposed to give the service account for gcloud at build time. But then again, I have different service account for each environment.

No, you don't have to give your credentials/service account key at build time. The client libraries are configured to read from environment variables and should work the same with native image compilation (it will try to read credentials from the environment).

I.e. GCloud or Environment variables should work the same. If deploying your container to a GCP environment (such as GCF, GKE, etc.) service account credentials should be automatically configured in the environment so things should work out of the box.

**Comment by christiangoudreau** [comment]
Yeah, after dumbing down a bit my dependencies, I got it to run correctly. The only problem was my conditionnal logback config where I was sending logs to the console in development rather than Google logging and trace.

**Comment by suztomo** [comment]
Thank you for update! Glad to hear it's resolved.
