### ISSUE TITLE
Help wanted: confusing version numbers

### ISSUE THREAD

**Issue by zp-chen-hkmci** [GoogleCloudPlatform/native-image-support-java#371]
According to README and github release, we are now at version 0.10.0

![image](https://user-images.githubusercontent.com/68260774/164434806-c1b7eb42-3b0e-4455-b71f-7ff6dbc05523.png)

![image](https://user-images.githubusercontent.com/68260774/164434926-ac6d541c-4b17-4c62-8c75-baca7a276288.png)

But I found the newer version on the maven Repository: https://search.maven.org/artifact/com.google.cloud/native-image-support/0.13.1/jar

![image](https://user-images.githubusercontent.com/68260774/164435425-821bc16f-3db9-40dc-9cb1-c8b8a19da2c4.png)

The new version has a completely different directory structure than the one in this repository

![image](https://user-images.githubusercontent.com/68260774/164435721-03cdbe01-dff8-49d8-9733-bffb93416539.png)

I'm very confused now, which version of native-image-support-java has been released up to. And these new versions don't contain the same content as the old ones.

Did i made something wrong? Or is it the new version with a new usage mechanism?

**Comment by zhumin8** [comment]
update: now the newest release is [v0.14.0](https://github.com/GoogleCloudPlatform/native-image-support-java/releases/tag/0.14.0) in this repo.
