### ISSUE TITLE
IllegalAccessError accessing graalvm module

### ISSUE THREAD

**Issue by javamachr** [GoogleCloudPlatform/native-image-support-java#434]
Using  Java Version info: 'GraalVM 22.2.0 Java 17 CE':
I keep getting this error when trying to build native image:
```
Fatal error: java.lang.IllegalAccessError: class com.google.cloud.sql.nativeimage.CloudSqlFeature (in unnamed module @0x6779959d) cannot access class com.oracle.svm.core.configure.ResourcesRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.configure to unnamed module @0x6779959d
        at com.google.cloud.sql.nativeimage.CloudSqlFeature.beforeAnalysis(CloudSqlFeature.java:55)

```

**Comment by jakubbadecki** [comment]
@javamachr As a workaround adding `--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED` to java args helped me to sort this issue.

**Comment by mpeddada1** [comment]
Thanks for creating the issue! I noticed that this was addressed in https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/998. Please note that this repo is experimental and will soon be archived. If the issue still persists, or for any new issues related to JDBC Socket Factory, please report to cloud-sql-jdbc-socket-factory repo directly.
